### ISSUE TITLE
healthcheck for config-server not working

### ISSUE THREAD

**Issue by dyroberts** [pivotal-cf/spring-cloud-services-starters#178]
Client app (v3.2.0.RELEASE) with:
```
management:
  endpoint:
    health:
      show-components: always
```
results in the following result from `/actuator/health`

```
{"status":"UP","components":{"clientConfigServer":{"status":"UNKNOWN","details":{"error":"no property sources located"}}, ...
```
